import { CloudProviderTag, DevelopmentTag, DifficultyTag, ExperienceTag, FrameworkTag, InterestTag, LanguageTag, SizeTag } from '../API'

export const Languages: LanguageTag[] = [
  LanguageTag.C,
  LanguageTag.JAVA,
  LanguageTag.PYTHON,
  LanguageTag.C_PLUS_PLUS,
  LanguageTag.CUDA,
  LanguageTag.C_SHARP,
  LanguageTag.JAVASCRIPT,
  LanguageTag.HTML,
  LanguageTag.CSS,
  LanguageTag.PHP,
  LanguageTag.VISUAL_BASIC_DOTNET,
  LanguageTag.DOTNET,
  LanguageTag.R,
  LanguageTag.GO,
  LanguageTag.SWIFT,
  LanguageTag.PERL,
  LanguageTag.X86_ASSEMBLY,
  LanguageTag.ARM_ASSEMBLY,
  LanguageTag.RUBY,
  LanguageTag.MATLAB,
  LanguageTag.VISUAL_BASIC,
  LanguageTag.GROOVY,
  LanguageTag.OBJECTIVE_C,
  LanguageTag.OBJECTIVE_C_PLUS_PLUS,
  LanguageTag.RUST,
  LanguageTag.SAS,
  LanguageTag.SCRATCH,
  LanguageTag.WEB_ASSEMBLY,
  LanguageTag.D,
  LanguageTag.DART,
  LanguageTag.PL_SQL,
  LanguageTag.SQL,
  LanguageTag.DELHPI,
  LanguageTag.KOTLIN,
  LanguageTag.OPENEDGE_ABL,
  LanguageTag.JULIA,
  LanguageTag.SCALA,
  LanguageTag.LUA,
  LanguageTag.FORTRAN,
  LanguageTag.COBOL,
  LanguageTag.HASKELL,
  LanguageTag.VISUAL_BASIC_SCRIPT,
  LanguageTag.TYPESCRIPT,
  LanguageTag.BASH,
  LanguageTag.SHELL,
  LanguageTag.CLOJURE,
  LanguageTag.COFFEESCRIPT,
  LanguageTag.LISP,
  LanguageTag.CRYSTAL,
  LanguageTag.F_SHARP,
  LanguageTag.POSTSCRIPT,
  LanguageTag.HANDLEBARS
]

export const Developments: DevelopmentTag[] = [
  DevelopmentTag.EMBEDDED_SYSTEMS,
  DevelopmentTag.FRONT_END,
  DevelopmentTag.WEB,
  DevelopmentTag.GAME_DEVELOPMENT,
  DevelopmentTag.MOBILE_APP,
  DevelopmentTag.COMPUTING,
  DevelopmentTag.APPLICATION_PROGRAMMING,
  DevelopmentTag.DEVOPS,
  DevelopmentTag.FULL_STACK,
  DevelopmentTag.BACKEND,
  DevelopmentTag.DATA_SCIENCE,
  DevelopmentTag.CLOUD,
  DevelopmentTag.DATABASE,
  DevelopmentTag.CYBERSECURITY
]

export const Frameworks: FrameworkTag[] = [
  FrameworkTag.DJANGO,
  FrameworkTag.ANGULAR_JS,
  FrameworkTag.JQUERY,
  FrameworkTag.ASP_NET,
  FrameworkTag.GATSBY,
  FrameworkTag.SVELTE,
  FrameworkTag.YII,
  FrameworkTag.TURBOGEARS,
  FrameworkTag.YESOD,
  FrameworkTag.GROK,
  FrameworkTag.MOJOLICIOUS,
  FrameworkTag.VAADIN,
  FrameworkTag.RUBY_ON_RAILS,
  FrameworkTag.EXPRESS,
  FrameworkTag.JS,
  FrameworkTag.METEOR,
  FrameworkTag.CODEIGNITOR,
  FrameworkTag.SYMFONY,
  FrameworkTag.APACHE_WICKET,
  FrameworkTag.PHALCON,
  FrameworkTag.BOOTSTRAP,
  FrameworkTag.SILEX,
  FrameworkTag.FUELPHP,
  FrameworkTag.CHERRYPY,
  FrameworkTag.QUIOXTE,
  FrameworkTag.LARAVEL,
  FrameworkTag.FLASK,
  FrameworkTag.CAKEPHP,
  FrameworkTag.NEXT_JS,
  FrameworkTag.GRAILS,
  FrameworkTag.SPARK,
  FrameworkTag.APACHE_STRUTS_1,
  FrameworkTag.WEB2PY,
  FrameworkTag.APACHE_PLAY,
]

export const Difficulty: DifficultyTag[] = [
  DifficultyTag.GOOD_FIRST_PROJECT,
  DifficultyTag.EXPERIENCED_CONTRIBUTOR,
  DifficultyTag.EXPERT,
]

export const CloudProviders: CloudProviderTag[] = [
  CloudProviderTag.AMAZON_WEB_SERVICES,
  CloudProviderTag.MICROSOFT_AZURE,
  CloudProviderTag.GOOGLE_CLOUD_PLATFORM,
  CloudProviderTag.SALESFORCE,
  CloudProviderTag.IBM_CLOUD,
  CloudProviderTag.HEROKU,
  CloudProviderTag.NETAPP,
]

export const Experience: ExperienceTag[] = [
  ExperienceTag.BEGINNER,
  ExperienceTag.MINIMAL_EXPERIENCE,
  ExperienceTag.EXPERIENCED_CONTRIBUTOR,
  ExperienceTag.EXPERT,
]

export const Size: SizeTag[] = [
  SizeTag.SMALL,
  SizeTag.MEDIUM,
  SizeTag.LARGE,
]

export const InterestTags: InterestTag[] = [
  InterestTag.COMMUNICATION,
  InterestTag.ENVIRONMENT,
  InterestTag.EDUCATION,
  InterestTag.ENTERTAINMENT,
  InterestTag.GAMING,
  InterestTag.HEALTHCARE,
  InterestTag.LIFESTYLE,
]

